# Generated by Django 6.0.3 on 2026-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('merchant', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
